# 46장 제너레이터와 async/await

# 46.1 제너레이터란?

- ES6에 도입
- 코드 블록의 실행을 **일시 중지했다가 필요한 시점에 재개**할 수 있는 특수한 함수다.
- 일반 함수 vs 제너레이터
    
    
    |  | 일반 함수 | 제너레이터 |
    | --- | --- | --- |
    | 함수 호출자에게 제어권 양도 | 불가능 | 가능 |
    | 함수 호출자와 상태를 주고 받음 | - 외부 → 내부 (by 매개변수)
    - 함수가 실행되는 동안에는 불가능 | 양방향으로 상태 전달 가능 |
    | 함수 호출 시 | 코드를 실행하고 값을 반환 | 이터러블이면서 이터레이터인 제너레이터 객체 반환 |

# 46.2 제너레이터 함수의 정의

- `function*` 키워드로 선언
    - 애스터리스크(*)의 위치는 function 키워드와 함수 이름 사이라면 어디든지 상관없다.
    - 일관성을 위해 function 키워드 **바로 뒤**에 붙이는 것을 권장한다.
- 하나 이상의 `yield` 표현식을 포함함
    
    ```jsx
    function* genDecFunc(){
    	yield 1;
    }
    
    const genDecFunc = function* (){
    	yield 1;
    }
    
    const obj = {
    	* genDecFunc(){
    		yield 1;
    	}
    }
    
    class MyClass {
    	* genDecFunc(){
    		yield 1;
    	}
    }
    ```
    
- 제너레이터 함수는 **화살표 함수로 정의할 수 없다.**
- 제너레이터 함수는 new 연산자와 함께 **생성자 함수로 호출할 수 없다.**

# 46.3 제너레이터 객체

- 제너레이터 함수를 호출하면 **제너레이터 객체**를 생성해 반환한다.
    - 제너레이터 객체는 **이터러블**이면서 **이터레이터**이다.
        - * 이터러블 : Symbol.iterator 메서드를 상속받음
        - * 이터레이터 : value, done 프로퍼티를 갖는 객체를 반환하는 **next** 메서드 소유
    
    ```jsx
    function* genFunc(){
    	yield 1;
    	yield 2;
    	yield 3;
    }
    
    const generator = genFunc();
    
    //이터러블
    console.log(Symbol.iterator in generator); // true
    
    //이터레이터
    console.log('next' in generator); //true
    ```
    
- 제너레이터 객체는 이터레이터지만, 이터레이터에는 없는 **return, throw** 메서드를 갖는다.
    - return 메서드 호출 시 {value: yield된 값, done: true}인 이터레이터 리절트 객체를 반환한다.
    - throw 메서드 호출 시 에러를 발생시키고 { value: undefined, done: true}인 이터레이터 리절트 객체를 반환한다.
    
    ```jsx
    function* genFunc(){
    	try {
    		yield 1;
    		yield 2;
    		yield 3;
    	} catch(e) {
    		console.error(e);
    	}
    }
    
    const generator = genFunc();
    
    // 1. return 호출 시
    console.log(generator.next()); // { value: 1, done: false }
    console.log(generator.return('End!')); // { value: 'End!', done: true}
    
    // 2. throw 호출 시
    console.log(generator.next()); // { value: 1, done: false }
    console.log(generator.throw('Error!')); // { value: undefined, done: true}
    ```
    

# 46.4 제너레이터의 일시 중지와 재개

- 제너레이터는 yield키워드와 next 메서드를 통해 실행을 일시 중지했다가 필요한 시점에 다시 재개할 수 있다.
- yield 키워드는 제너레이터 함수의 실행을 일시 중지 시키거나
yield 키워드 뒤의 표현식 평가 결과를 제너레이터 함수 호출자에 반환한다.
    
    ```jsx
    function* genFunc(){
    	yield 1;
    	yield 2;
    	yield 3;
    }
    
    const generator = genFunc();
    
    // 첫번째 yield 뒤의 표현식 평가 결과 1 반환
    console.log(generator.next()); // { value: 1, done: false }
    // 두번째 yield 뒤의 표현식 평가 결과 2 반환
    console.log(generator.next()); // { value: 2, done: false }
    // 세번째 yield 뒤의 표현식 평가 결과 3 반환
    console.log(generator.next()); // { value: 3, done: false }
    
    // 남은 yield 표현식이 없으므로 제너레이터 함수의 마지막까지 실행한다.
    // value에는 **제너레이터 함수의 반환값** undefined가 할당된다.
    console.log(generator.next()); // { value: undefined, done: true}
    ```
    
    이처럼 next 메서드를 반복 호출하여 yield 표현식까지 실행과 일시 중지를 반복하다가 끝까지 실행되면 제너레이터의 반환값이 value에, true가 done에 할당된다.
    
    ```jsx
    generator.next() -> yield -> generator.next() => yield -> ... -> generator.next() -> return
    ```
    
    **제너레이터 객체의 next 메서드에 전달한 인수는 yield 표현식을 할당받는 변수에 할당된다.**
    
    ```jsx
    function* genFunc(){
    	const x = yield 1;
    	const y = yield (x + 10);
    	return x + y;
    }
    
    const generator = genFunc(0);
    
    console.log(generator.next()); // { value: 1, done: false }
    
    //next 메서드에 전달한 인수 10은 genFunc 함수의 **x변수에 할당**된다.
    // 10 + 10 = 20
    console.log(generator.next(10)); // { value: 20, done: false }
    
    //next 메서드에 전달한 인수 20은 genFunc 함수의 **y변수에 할당**된다.
    // 10 + **20** = 30
    console.log(generator.next(20)); // { value: 30, done: true }
    ```
    
- 제너레이터의 특성을 활용하면 **비동기 처리를 동기 처리처럼 구현할 수 있다.**

# 46.5 제너레이터 활용

## 46.5.1 이터러블의 구현

- 제너레이터 함수를 사용하면 이터레이션 프로토콜을 준수해 이터러블을 생성하는 방식보다 간단히 이터러블을 구현할 수 있다.
- ex) 무한 피보나치 수열을 생성하는 함수
    1. 이터러블 프로토콜을 준수한 이터러블
        
        ```jsx
        const infiniteFibonacchi = (function() {
        	let [pre, cur] = [0, 1];
        
        	return {
        		[Symbol.iterator]() { return this; },
        		next() {
        			[pre, cur] = [cur, pre + cur];
        			return { value: cur };
        		}
        	}
        }());
        
        for (const num of infiniteFibonacci){
        	if(num > 10000) break;
        	console.log(num); // 1 2 3 5 8 ...
        }
        ```
        
    2. 제너레이터 
        
        ```jsx
        const infiniteFibonacchi = (function* () {
        	let [pre, cur] = [0, 1];
        
        	while (true) {
        		[pre, cur] = [cur, pre + cur];
        		yield cur;
        	}
        }());
        
        for (const num of infiniteFibonacci){
        	if(num > 10000) break;
        	console.log(num); // 1 2 3 5 8 ...
        }
        ```
        

## 46.5.2 비동기 처리

- 제너레이터의 특성을 활용하면 프로미스를 사용한 비동기 처리를 동기 처리처럼 구현할 수 있다.
    - 즉, **then/catch/finally 없이** 비동기 처리 결과를 반환하도록 구현할 수 있다.
    
    ```jsx
    const fetch = require('node-fetch');
    
    const async = generatorFunc => {
    	const generator = generatorFunc(); 
    	
    	const onResolved = arg => {
    		const result = generator.next(arg);
    
    		return result.done
    			? result.value : result.value.then(res -> onResolved(res));
    	}
    
    	return onResolved;
    }
    
    (async(function* fetchTodo() {
    	const url = "https://jsonplaceholder.typicode.com/todos/1";
    
    	const response = yield fetch(url);
    	const todo = yield response.json();
    	console.log(todo);
    })());
    ```
    
    - async/await를 사용하면 위와 같은 제너레이터 실행기를 사용할 필요가 없지만, 필요하다면 직접 구현하는 것보다 `co 라이브러리`를 사용한다.

# 46.6 async/await

- ES8에서는 제너레이터보다 간단하고 가독성 좋게 비동기 처리를 동기처럼 동작할 수 있도록 구현할 수 있는 **async/await**가 도입되었다.
- async/await를 사용하면 then/catch/finally로 후속 처리할 필요 없이 동기처럼 프로미스를 사용할 수 있다.
    
    ```jsx
    const fetch = require('node-fetch');
    
    async function fetchTodo () {
    	const url = "https://jsonplaceholder.typicode.com/todos/1";
    	
    	const response = await fetch(url);
    	const todo = await response.json();
    	console.log(todo);
    }
    
    fetchTodo();
    ```
    

## 46.6.1 async 함수

- await 키워드는 반드시 async 함수 내부에서 사용해야 한다.
- async 함수는 **언제나 암묵적으로 반환값을 resolve 하는 프로미스를 반환한다.**
    
    ```jsx
    async function foo(n) { return n; }
    foo(1).then(v => console.log(v)); //1
    
    const bar = async function (n) { return n; };
    bar(2).then(v => console.log(v)); //2
    
    const baz = async n => n;
    baz(3).then(v => console.log(v)); // 3
    
    const obj = {
    	asnyc foo(n) { return n; }
    };
    obj.foo(4).then(v => console.log(v)); // 4
    
    class MyClass {
    	async bar(n) { return n; }
    }
    const myClass = new MyClass();
    myClass.bar(5).then(v => console.log(v)); // 5
    ```
    
    - 클래스의 constructor 메서드는 언제나 인스턴스를 반환 해야하기 때문에 **async 메서드가 될 수 없다.**

## 46.6.2 await 키워드

- 프로미스가 settled 상태가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 resolve 한 처리 결과를 반환한다.
- **await 키워드는 반드시 프로미스 앞에서 사용해야 한다.**
- 모든 프로미스에 await 키워드를 사용하는 것은 주의해야 한다.
    
    ```jsx
    async function foo() {
    	const a = await new Promise(resolve => setTimeout(() => resolve(1), 3000));
    	const b = await new Promise(resolve => setTimeout(() => resolve(2), 2000));
    	const c = await new Promise(resolve => setTimeout(() => resolve(3), 1000));
    
    	console.log([a, b, c]); // [1, 2, 3]
    }
    
    foo();// 6초 소요
    ```
    
    **연관이 없는 비동기 처리**는 순차적으로 처리할 필요가 없다.
    
    ```jsx
    async function foo() {
    	const res = await Promise.all([
    		new Promise(resolve => setTimeout(() => resolve(1), 3000));
    		new Promise(resolve => setTimeout(() => resolve(2), 2000));
    		new Promise(resolve => setTimeout(() => resolve(3), 1000));
    	]);
    	
    	console.log([a, b, c]); // [1, 2, 3]
    }
    
    foo(); // 3초 소요
    ```
    
    처리 순서가 보장되어야 하는 경우(앞선 비동기 결과를 갖고 다음 비동기 처리를 수행해야 하는 경우) 모든 프로미스에 await 키워드를 써서 순차적으로 처리할 수밖에 없다.
    
    ```jsx
    async function bar(n) {
    	const a =	new Promise(resolve => setTimeout(() => resolve(n), 3000));
    	const b =	new Promise(resolve => setTimeout(() => resolve(a + 1), 2000));
    	const c =	new Promise(resolve => setTimeout(() => resolve(b + 1), 1000));
    	
    	console.log([a, b, c]); // [1, 2, 3]
    }
    
    foo(); //6초 소요
    ```
    

## 46.6.3 ⭐ 에러 처리

- 비동기 처리를 위한 콜백 패턴의 가장 큰 단점은 **에러처리**이다.
    - ⭐ 에러는 **호출자** 방향으로 전파된다.
    - 하지만 비동기 함수의 콜백 함수를 호출한 것은 비동기 함수가 아니기 때문에 **try … catch 문을 사용해 에러를 캐치할 수 없다.**
        
        ```jsx
        try {
        	setTimeout(() => { throw new Error('Error!'); }, 1000);
        } catch (e) {
        	**// 에러를 캐치하지 못한다**
        	console.error(e);
        }
        ```
        
    - async/await 문에서는 try…catch 문을 사용할 수 있다. 콜백함수를 인수로 받는 비동기 함수와 다르게, 프로미스를 반환하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 **호출자가 명확하다.**
        
        ```jsx
        const fetch = require('node-fetch');
        
        const foo = async () => {
        	try {
        		const wrongUrl= "https://wrong.url";
        
        		const response = await fetch(wrongUrl);
        		const data = await response.json();
        		console.log(data);
        	}catch (err){
        		console.error(err); // TypeError: Fail to fetch
        	}
        };
        
        fetchTodo();
        ```
        
        HTTP 통신에서 발생한 네트워크 에러 뿐만 아니라 **try 코드 블록 내의 모든 에러를 캐치할 수 있다.**
        
        async 함수 내에서 catch 문을 사용해 에러처리를 하지 않으면 async 함수는 에러를 reject 하는 프로미스를 반환한다. ⇒ **Promise.prototype.catch 후속 처리 메서드**로 에러를 캐치할 수도 있다.
        
        ```jsx
        const fetch = require('node-fetch');
        
        const foo = async () => {
        	const wrongUrl= "https://wrong.url";
        
        	const response = await fetch(wrongUrl);
        	const data = await response.json();
        	return data;
        };
        
        foo()
        	.then(console.log)
        	.catch(console.error); //TypeError: Failed to data
        ```