# 45장 프로미스

- ES6에서 비동기 처리를 위한 패턴으로 프로미스를 도입했다.
- **전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다.**

# 45.1 비동기 처리를 위한 콜백 패턴의 단점

## 45.1.1 콜백 헬

```jsx
const get = url => {
	const xhr = XMLHttpRequest();
	xhr.open('GET', url);
	xhr.send();

	xhr.onload = () => { // 비동기로 동작
		if(xhr.status === 200) {
			console.log(JSON.parse(xhr.response));
		}else {
			console.log(`${xhr.status} ${xhr.statusText}`);		
		}
	}
}

get('https://jsonplaceholder.typicode.com/posts/1');

/*
{
	"userId": 1,
	"id": 1
	...
}
*/
```

- 여기서 get 함수는서버의 응답 결과를 콘솔에 출력한다. get함수가 서버의 응답 결과를 반환하게 하려면 어떻게 하면 될까?
- get 함수는 비동기 함수다. 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. **따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프에 변수를 할당하면 기대한 대로 동작하지 않는다.**
- 예를 들어 setTimeout 함수 내부의 콜백 함수에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.
    
    ```jsx
    let g = 0;
    
    setTimeout(() => { g = 100; }, 0};
    console.log(g); // 0
    ```
    

- 비동기 함수는 **비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수 없다.** 따라서 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.
- 일반적으로 비동기 함수에 처리 결과에 대한 후속 처리를 수행하는 **콜백 함수**를 전달하는 것이 일반적이다.
    
    ```jsx
    const get = (url, **successCallback, failureCallback**) => {
    	const xhr = XMLHttpRequest();
    	xhr.open('GET', url);
    	xhr.send();
    
    	xhr.onload = () => { // 비동기로 동작
    		if(xhr.status === 200) {
    			successCallback(JSON.parse(xhr.response));
    		}else {
    			failureCallback(xhr.status);
    		}
    	}
    }
    
    get('https://jsonplaceholder.typicode.com/posts/1');
    ```
    
- 이처럼 콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면, 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생한다. 이를 `**콜백 헬**`이라고 한다.
    - 콜백 헬은 가독성을 나쁘게 하며 실수를 유발하는 원인이 된다
    
    ```jsx
    get('/step1', a => {
    	get(`/step2/${a}`, b => {
    		get(`/step3/${b}`, c => {
    			get(`/step4/${c}`, d => {
    				console.log(d);
    			});
    		});
    	});
    });
    ```
    

## 45.1.2 에러 처리의 한계

- 비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 **에러 처리가 곤란하다는 것이다.**
    
    ```jsx
    try {
    	setTimeout(() => { throw new Error('Error!'); }, 1000);
    } catch(e){
    	//에러를 캐치하지 못한다.
    	console.log('캐치한 에러', e);
    }
    ```
    
    setTimeout 함수의 콜백 함수가 실행될 때 setTimeout함수는 이미 콜 스택에서 제거된 상태이다. 이것은 setTimeout함수의 콜백 함수를 호출한 것이 setTimeout이 아니라는 것을 의미한다.
    **에러는 호출자 방향으로 전파된다. setTimeout함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니므로, setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.**
    
- 비동기 처리를 위한 콜백 패턴은 `콜백 헬`과 `에러처리`가 곤란하다는 문제가 있다. 이를 해결하기 위해 ES6에서 프로미스가 도입됐다.

# 45.2 프로미스의 생성

- Promise 생성자 함수를 new와 함께 호출하면 프로미스를 생성한다. Promise는 표준 빌트인 객체다.
    - Promise 생성자 함수는 비동기 처리를 수행할 콜백함수를 인수로 전달 받는데, 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.
    
    ```jsx
    const promise = new Promise((resolve, reject) => {
    	if( 비동기 처리 성공 ){
    		resolve('result');
    	} else {
    		reject('failure reason');
    	}
    });
    ```
    
- 앞에서 살펴본 비동기 함수 get을 프로미스를 사용해 다시 구현해보자.

```jsx
const promiseGet = (url) => {
	return new Promise((resolve, reject) => {
		const xhr = XMLHttpRequest();
		xhr.open('GET', url);
		xhr.send();
	
		xhr.onload = () => { // 비동기로 동작
			if(xhr.status === 200) {
				successCallback(JSON.parse(xhr.response));
			}else {
				failureCallback(xhr.status);
			}
		};
	});
};

//프로미스 반환
promiseGet ('https://jsonplaceholder.typicode.com/posts/1');
```

- 프로미스는 다음과 같이 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 갖는다.
    
    
    | 프로미스 상태 정보 | 의미 | 상태 변경 조건 |
    | --- | --- | --- |
    | pending |  비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
    | fulfilled | 비동기 처리가 수행된 상태(성공) | resolve 함수 호출 |
    | rejected | 비동기 처리가 수행된 상태(실패) | reject 함수 호출 |
    - 비동기 처리 성공: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경.
    - 비동기 처리 실패: reject 함수를 호출해 프로미스를 rejected 상태로 변경.
- 비동기 처리가 성공하면 프로미스는 pending 상태에서 fulfilled 상태로 변화한다. 그리고 비동기 처리 결과인 1을 값으로 갖는다.
- 비동기 처리가 실패하면 프로미스는 pending 상태에서 rejected 상태로 변화한다. 그리고 비동기 처리 결과인 Error객체를 값으로 갖는다.
- **즉, 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.**

# 45.3 프로미스의 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.

## 45.3.1 Promise.prototype.then

- then은 두 개의 콜백 함수를 인수로 받는다.
    - 첫 번째 콜백함수는 프로미스가 fulfilled 상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
    - 두 번째 콜백함수는 프로미스가 rejected 상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
    
    ```jsx
    new Promise(resolve => resolve('fulfilled'));
    	.then(v => console.log(v), e => console.error(e));
    
    new Promise(resolve => resolve('rejected'));
    	.then(v => console.log(v), e => console.error(e));
    ```
    

## 45.3.2 Promise.prototype.catch

- catch 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- catch 메서드의 콜백 함수는 프로미스가 **rejected** 상태인 경우에만 호출된다.
- catch는 then과 동일하게 동작한다. 언제나 프로미스를 반환한다.

## 45.3.3 Promise.prototype.finally

- finally 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- fulfilled와 rejected에 상관 없이 무조건 한 번은 호출된다.
    
    ⇒ 프로미스 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 사용.
    
- 언제나 프로미스를 반환한다.

# 45.4 프로미스의 에러 처리

- 비동기 처리를 위한 콜백 패턴은 에러 처리가 곤란하다는 문제가 있다.
- 프로미스를 사용하면 **then 메서드의 두 번째 콜백함수** 또는 **프로미스의 후속처리 메서드 catch**로 처리할 수 있다.
    - catch를 호출하면 내부적으로 then(undefined, onRejected)을 호출한다.
    - **then 메서드의 두 번째 콜백함수는 첫 번째 콜백함수에서 발생한 에러를 캐치하지 못하고, 코드가 복잡해져서 가독성이 좋지 않다.**
    - catch 메서드를 모든 then 메서드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러 뿐만 아니라 then 메서드 내부에서 발생한 에러까지도 모두 해결할 수 있다.

# 45.5 프로미스 체이닝

- then, catch, finally 후속 처리 메서드는 콜백 함수가 반환한 프로미스를 반환한다.
- 콜백 함수가 프로미스가 아닌 값을 반환하더라도 그 값을 암묵적으로 resolve 또는 reject해서 프로미스를 생성해 반환한다.
- 프로미스는 프로미스 체이닝을 통해 후속 처리를 하므로 **콜백 헬이 발생하지 않는다**. 다만 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다.
- **콜백 패턴은 가독성이 좋지 않다.** 이 문제는 ES8에서 도입된 `async/await`를 통해 해결할 수 있다. `async/await`를 사용하면 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다.
    
    ```jsx
    const url = '...';
    
    (async () => {
    	const { userId } = await promiseGet(`${url}/posts/1`);
    
    	const userInfo = await promiseGet(`${url}/users/${userId}`);
    })();
    ```
    
    asnyc/await도 프로미스를 기반으로 동작하므로 프로미스는 잘 이해하고 있어야 한다.
    

# 45.6 프로미스의 정적 메서드

- Promise는 5가지 정적 메서드를 제공한다.

## 45.6.1 Promise.resolve / Promise.reject

- 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.
- Promise.resolve는 인수로 전달받은 값을 resolve하는 프로미스를 생성한다.
    
    ```jsx
    const resolvedPromise = Promise.resolve([1, 2, 3]);
    resolvedPromise.then(console.log); // [1, 2, 3]
    
    const rejectedPromise = Promise.reject(new Error('Error!');
    rejectedPromise.catch(console.log); // Error: Error!
    ```
    

## 45.6.2 Promise.all

- 여러 개의 비동기 처리를 **모두 병렬로 처리할 때** 사용.

```jsx
const requestData1 = () =>
	new Promise(resolve => setTimeout(()=> resolve(1), 3000));
const requestData2 = () =>
	new Promise(resolve => setTimeout(()=> resolve(2), 2000));
const requestData3 = () =>
	new Promise(resolve => setTimeout(()=> resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()]);
	.then(console.log);
	.catch(console.log);
```

- 전달받은 모든 프로미스가 모두 fulfilled 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다.
- 처리 순서가 보장된다.
- 하나라도 rejected상태가 되면 나머지 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고 즉시 공유한다.
- Promise.all 메서드는 인수로 전달받은 이터러블 요소가 프로미스가 아닌 경우, Promise.resolve 메서드를 통해 프로미스로 래핑한다.
    
    ```jsx
    Promise.all([
    	1, // Promise.resolve(1)
    	2, // Promise.resolve(2)
    	3  // Promise.resolve(3) 
    ])
    ```
    

## 45.6.3 Promise.race

- Promise.all 메서드처럼 이터러블을 인수로 전달받지만, 모든 프로미스가 fulfilled 상태가 되길 기다리는 것이 아니라, 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve 하는 새로운 프로미스를 반환한다.
- 프로미스가 하나라도 rejected 상태가되면 에러를 reject하는 새로운 프로미스를 즉시 반환한다.

## 45.6.4 Promise.allSettled

- 이터러블을 인수로 전달받는다.
- 프로미스가 모두 settled 상태가 되면 처리 결과를 배열로 반환한다.

# 45.7 마이크로태스크 큐

- 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로 태스크 큐에 저장된다.
- 콜백 함수나 이벤트 핸들러를 저장한다는 점에서 태스크와 동일하지만, 마이크로 테스크 큐는 태스크 큐보다 우선순위가 높다.

## 45.8 fetch

- fetch함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 지원하는 클라이언트 사이드 Web API이다.
    - XMLHttpRequest보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.
- fetch 함수는HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.
- fetch 함수가 반환하는 프로미스는 기본적으로 404, 500와 같은 HTTP 에러가 발생하도 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve한다.
- CORS 에러나 네트워크 장애 등의 이유로 요청이 완료되지 못한 경우에만 프로미스를 reject한다.
- fetch함수를 사용할 때는 fetch 함수가 반환한 프로미스가 resolve한 **불리언 타입의 ok 상태를 확인해** 명시적으로 에러를 처리할 필요가 있다.

```jsx
const wrongUrl = "...";

fetch(wrongUrl)
	.then(response => {
		if(!response.ok) throw new Error(response.statusText);
	})
	.then(todo => console.log(todo));
	.catch(err => console.error(err));
```

- fetch 함수를 통해 HTTP 요청을 전송해보자. 첫번째 인수로 url, 두번째 인수로 요청 메서드  , HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.

```jsx
const request = {
	get(url){
		return fetch(url);
	},

	post(url, payload){
		return fetch(url, {
			method: 'POST',
			headers: { 'content-Type' : 'application/json' },
			body: JSON.stringfy(payload)
		});
	},

	patch(url, payload){
		return fetch(url, {
			method: 'PATCH',
			headers: { 'content-Type' : 'application/json' },
			body: JSON.stringfy(payload)
		});
	},

	delete(url){
		return fetch(url, {method: 'DELETE' });
	},
}
```

### 1. GET 요청

```jsx
request.get('https://jsonplaceholder.typicode.com/todos/1')
	.then(response =>{
		if(!response.ok) throw new Error(response.statusText);
		return response.json();
	});
	.then(todos => console.log(todos));
	.catch(err => console.log(err));
```

### 2. POST 요청

```jsx
request.post('https://jsonplaceholder.typicode.com/todos/1', {
		userId: 1,
		title: 'Javascript',
		completed: false
	})
	.then(response =>{
		if(!response.ok) throw new Error(response.statusText);
		return response.json();
	});
	.then(todos => console.log(todos));
	.catch(err => console.log(err));
```

### 3. PATCH 요청

```jsx
request.patch('https://jsonplaceholder.typicode.com/todos/1', {
	completed: true
}).then(response =>{
	if(!response.ok) throw new Error(response.statusText);
		return response.json();
	});
	.then(todos => console.log(todos));
	.catch(err => console.log(err));
```

### 4. DELETE 요청

```jsx
request.delete('https://jsonplaceholder.typicode.com/todos/1')
	.then(response =>{
		if(!response.ok) throw new Error(response.statusText);
		return response.json();
	});
	.then(todos => console.log(todos));
	.catch(err => console.log(err));
```

---

### *axios

- 모든 HTTP 에러를 reject하는 프로미스를 반환한다. 따라서 모든 에러를 catch에서 처리할 수 있어서 편하다.
- axios는 인터셉터, 요청 설정 등 fetch보다 다양한 기능을 지원한다.